# Generated by Django 6.0.4 on 2026-05-08 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_record_sales', models.BooleanField(default=True)),
                ('manager_view_sales', models.BooleanField(default=True)),
                ('manager_void_sale', models.BooleanField(default=True)),
                ('manager_add_products', models.BooleanField(default=True)),
                ('manager_edit_products', models.BooleanField(default=True)),
                ('manager_delete_products', models.BooleanField(default=True)),
                ('manager_record_restock', models.BooleanField(default=True)),
                ('manager_view_analytics', models.BooleanField(default=True)),
                ('manager_invite_members', models.BooleanField(default=False)),
                ('manager_manage_branches', models.BooleanField(default=False)),
                ('cashier_record_sales', models.BooleanField(default=True)),
                ('cashier_view_sales', models.BooleanField(default=True)),
                ('cashier_void_sale', models.BooleanField(default=False)),
                ('cashier_add_products', models.BooleanField(default=False)),
                ('cashier_edit_products', models.BooleanField(default=False)),
                ('cashier_delete_products', models.BooleanField(default=False)),
                ('cashier_record_restock', models.BooleanField(default=False)),
                ('cashier_view_analytics', models.BooleanField(default=False)),
                ('cashier_invite_members', models.BooleanField(default=False)),
                ('cashier_manage_branches', models.BooleanField(default=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_privileges', to='business.business')),
            ],
            options={
                'db_table': 'role_privileges',
            },
        ),
    ]
