# Generated by Django 5.1.1 on 2026-05-14 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_roleprivilege'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPrivilegeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_sales', models.BooleanField(blank=True, null=True)),
                ('view_sales', models.BooleanField(blank=True, null=True)),
                ('void_sale', models.BooleanField(blank=True, null=True)),
                ('add_products', models.BooleanField(blank=True, null=True)),
                ('edit_products', models.BooleanField(blank=True, null=True)),
                ('delete_products', models.BooleanField(blank=True, null=True)),
                ('record_restock', models.BooleanField(blank=True, null=True)),
                ('view_analytics', models.BooleanField(blank=True, null=True)),
                ('invite_members', models.BooleanField(blank=True, null=True)),
                ('manage_branches', models.BooleanField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_overrides', to='business.business')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_override', to='business.branchmember')),
            ],
            options={
                'db_table': 'member_privilege_overrides',
            },
        ),
    ]
